name: "CI"

on:
  push:
    tags-ignore:
      - "*"
    branches:
      - "*"
  workflow_dispatch:

jobs:
  go_test:
    name: "Go Test"
    runs-on: ubuntu-latest

    steps:
      - name: "Go Setup"
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Test"
        run: |
          go test
